# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/psu_projects/ece544_winter15_projects/ip/ip_repo/pmod544ior2_1.0/pmod544ior2_v1_0_v1_0_project/PMod544IOR2_v1_0_v1_0_project.cache/wt [current_project]
set_property parent.project_path c:/psu_projects/ece544_winter15_projects/ip/ip_repo/pmod544ior2_1.0/pmod544ior2_v1_0_v1_0_project/PMod544IOR2_v1_0_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths C:/PSU_Projects/ECE544_Winter15_Projects/IP/ip_repo [current_project]
read_verilog -library xil_defaultlib {
  c:/psu_projects/ece544_winter15_projects/ip/ip_repo/pmod544ior2_1.0/src/rotary_filter.v
  c:/psu_projects/ece544_winter15_projects/ip/ip_repo/pmod544ior2_1.0/src/pblaze_if.v
  c:/psu_projects/ece544_winter15_projects/ip/ip_repo/pmod544ior2_1.0/src/kcpsm6.v
  c:/psu_projects/ece544_winter15_projects/ip/ip_repo/pmod544ior2_1.0/src/ECE544ifpgm.v
  c:/psu_projects/ece544_winter15_projects/ip/ip_repo/pmod544ior2_1.0/src/ECE544if_core.v
  c:/psu_projects/ece544_winter15_projects/ip/ip_repo/pmod544ior2_1.0/src/debounce.v
  c:/psu_projects/ece544_winter15_projects/ip/ip_repo/pmod544ior2_1.0/hdl/PMod544IOR2_v1_0_S00_AXI.v
  c:/psu_projects/ece544_winter15_projects/ip/ip_repo/pmod544ior2_1.0/hdl/PMod544IOR2_v1_0.v
}
catch { write_hwdef -file PMod544IOR2_v1_0.hwdef }
synth_design -top PMod544IOR2_v1_0 -part xc7a100tcsg324-1
write_checkpoint -noxdef PMod544IOR2_v1_0.dcp
catch { report_utilization -file PMod544IOR2_v1_0_utilization_synth.rpt -pb PMod544IOR2_v1_0_utilization_synth.pb }
